config/routes.rb
Rails.application.routes.draw do

  resources :rentals
  resources :rentals
  resources :rentals
  resources :rentals
  resources :lodgers
  resources :rooms
  resources :landlords

  root :to=> 'pages#home'

  
     controller :sessions do
       get 'login'=> :new
       post 'login' => :create
       get 'logout' => :destroy
       delete 'logout' => :destroy
     end
end

app/models/rental.rb
class Rental < ActiveRecord::Base
end

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  before_action :set_rental, only: [:show, :edit, :update, :destroy]

  # GET /rentals
  # GET /rentals.json
  def index
    @rentals = Rental.all
  end

  # GET /rentals/1
  # GET /rentals/1.json
  def show
  end

  # GET /rentals/new
  def new
    @rental = Rental.new
  end

  # GET /rentals/1/edit
  def edit
  end

  # POST /rentals
  # POST /rentals.json
  def create
    @rental = Rental.new(rental_params)

    respond_to do |format|
      if @rental.save
        format.html { redirect_to @rental, notice: 'Rental was successfully created.' }
        format.json { render :show, status: :created, location: @rental }
      else
        format.html { render :new }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rentals/1
  # PATCH/PUT /rentals/1.json
  def update
    respond_to do |format|
      if @rental.update(rental_params)
        format.html { redirect_to @rental, notice: 'Rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @rental }
      else
        format.html { render :edit }
        format.json { render json: @rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rentals/1
  # DELETE /rentals/1.json
  def destroy
    @rental.destroy
    respond_to do |format|
      format.html { redirect_to rentals_url, notice: 'Rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rental
      @rental = Rental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rental_params
      params.require(:rental).permit(:room_address, :lodger_name, :lease_start, :lease_end)
    end
end

app/helpers/rentals_helper.rb
module RentalsHelper
end

app/views/rentals/_form.html.erb
<%= form_for(@rental) do |f| %>
  <% if @rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rental.errors.count, "error") %> prohibited this rental from being saved:</h2>

      <ul>
      <% @rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :room_address %><br>
   <%= f.collection_select :room_address,Room.all,  :address ,:address%>
  </div>
  <div class="field">
    <%= f.label :lodger_name %><br>   
    <%= f.collection_select :lodger_name,Lodger.all,  :name, :name %>
  </div>
  <div class="field">
    <%= f.label :lease_start %><br>
    <%= f.date_select :lease_start %>
  </div>
  <div class="field">
    <%= f.label :lease_end %><br>
    <%= f.date_select :lease_end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rentals/edit.html.erb
<h1>Editing Rental</h1>

<%= render 'form' %>

<%= link_to 'Show', @rental %> |
<%= link_to 'Back', rentals_path %>

app/views/rentals/index.html.erb
<h1>Listing Rentals</h1>

<table>
  <thead>
    <tr>
      <th>Room address</th>
      <th>Lodger name</th>
      <th>Lease start</th>
      <th>Lease end</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rentals.each do |rental| %>
      <tr>
        <td><%= rental.room_address %></td>
        <td><%= rental.lodger_name %></td>
        <td><%= rental.lease_start %></td>
        <td><%= rental.lease_end %></td>
        <td><%= link_to 'Show', rental %></td>
        <td><%= link_to 'Edit', edit_rental_path(rental) %></td>
        <td><%= link_to 'Destroy', rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rental', new_rental_path %>

app/views/rentals/new.html.erb
<h1>New Rental</h1>

<%= render 'form' %>

<%= link_to 'Back', rentals_path %>

app/views/rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Room address:</strong>
  <%= @rental.room_address %>
</p>

<p>
  <strong>Lodger name:</strong>
  <%= @rental.lodger_name %>
</p>

<p>
  <strong>Lease start:</strong>
  <%= @rental.lease_start %>
</p>

<p>
  <strong>Lease end:</strong>
  <%= @rental.lease_end %>
</p>

<%= link_to 'Edit', edit_rental_path(@rental) %> |
<%= link_to 'Back', rentals_path %>