config/routes.rb
Rails.application.routes.draw do

  resources :rentals
  resources :rentals
  resources :rentals
  resources :rentals
  resources :lodgers
  resources :rooms
  resources :landlords

  root :to=> 'pages#home'

  
     controller :sessions do
       get 'login'=> :new
       post 'login' => :create
       get 'logout' => :destroy
       delete 'logout' => :destroy
     end
end

app/models/landlord.rb
class Landlord < ActiveRecord::Base
  has_many :rooms, dependent: :destroy
  
  #validates_confirmation_of :password
  has_secure_password
  validates :password,
    :length => { :minimum => 6, :maximum =>10 }
  
  validates :name, presence: true
  validates :phone, presence: true

  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create
end

app/controllers/landlords_controller.rb
class LandlordsController < ApplicationController
  before_action :set_landlord, only: [:show, :edit, :update, :destroy]

  # GET /landlords
  # GET /landlords.json
  def index
    @landlords = Landlord.all
  end

  # GET /landlords/1
  # GET /landlords/1.json
  def show
  end

  # GET /landlords/new
  def new
    @landlord = Landlord.new
  end

  # GET /landlords/1/edit
  def edit
  end

  # POST /landlords
  # POST /landlords.json
  def create
    @landlord = Landlord.new(landlord_params)

    respond_to do |format|
      if @landlord.save
	     
         UserMailer.welcome(@landlord).deliver_now #this will send the email
        format.html { redirect_to @landlord, notice: 'Landlord was successfully created.' }
        format.json { render :show, status: :created, location: @landlord }
       
      else
        format.html { render :new }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
    

  end

  # PATCH/PUT /landlords/1
  # PATCH/PUT /landlords/1.json
  def update
    respond_to do |format|
      if @landlord.update(landlord_params)
        format.html { redirect_to @landlord, notice: 'Landlord was successfully updated.' }
        format.json { render :show, status: :ok, location: @landlord }
      else
        format.html { render :edit }
        format.json { render json: @landlord.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /landlords/1
  # DELETE /landlords/1.json
  def destroy
  @landlord.destroy
    respond_to do |format|
      format.html { redirect_to landlords_url, notice: 'Landlord was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_landlord
      @landlord = Landlord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def landlord_params
      params.require(:landlord).permit(:name, :email, :phone, :reviews, :room_id, :password,:password_confirmation)
    end
end

app/helpers/landlords_helper.rb
module LandlordsHelper
end

app/views/landlords/_form.html.erb
<%= form_for(@landlord) do |f| %>
  <% if @landlord.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@landlord.errors.count, "error") %> prohibited this landlord from being saved:</h2>

      <ul>
      <% @landlord.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  




<div class="container">
        <div class="row centered-form">
        <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
        	<div class="panel panel-default">
        		<div class="panel-heading">
			    		<h3 class="panel-title">Register as a lodger<small>It's free!</small></h3>
			 			</div>
			 			<div class="panel-body">
			    		<form role="form">
			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					
					<div class="form-group">
			                 <%= f.text_field :name , :placeholder=> "Enter Name Here"%>
			    		</div>
			    				</div>
			    				
			    			</div>

			    			<div class="form-group" align = "left">
			    			<%= f.text_field :email, :placeholder=>"Email" %>
			    			</div>

						<div class="form-group" align = "left">
			    				  <%= f.text_field :phone, :placeholder=>"Phone No." %>
			    			</div>

						



						

			    			<div class="row">
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
			    				 <%= f.password_field :password, :placeholder=>"Password (6-10)"%>
			    					</div>
			    				</div>
			    				<div class="col-xs-6 col-sm-6 col-md-6">
			    					<div class="form-group">
						 <%=f.password_field :password_confirmation , :placeholder=>"Confirm Password"%>
			    					</div>
			    				</div>
			    			</div>
			    			
						
						 <%= f.submit "Create Landlord", class: "btn btn-block btn-primary"  %>
			    			
						
			    		
			    		</form>
			    	</div>
	    		</div>
    		</div>
    	</div>
    </div>

<% end %>

app/views/landlords/edit.html.erb
<h1 align = "center">Editing Landlord</h1>

<%= render 'form' %>

<div align = "center">
<%= link_to 'Show', @landlord %> |
<%= link_to 'Back', landlords_path %>
</div>

app/views/landlords/index.html.erb
<h1 align = "center">Listing Landlords</h1>

<table class = "table table-bordered">
  <thead>
    <tr>
      <th style="text-align:center">Name</th>
      <th style="text-align:center">Email</th>
      <th style="text-align:center">Phone</th>
    
      <th style="text-align:center" colspan="3"><i>options</i></th>
    </tr>
  </thead>

  <tbody>
    <% @landlords.each do |landlord| %>
      <tr>
        <td><%= landlord.name %></td>
        <td><%= landlord.email %></td>
        <td><%= landlord.phone %></td>
      
       
	   <td style="text-align:center"><%= link_to 'Show', landlord %></td>
        <td style="text-align:center"><%= link_to 'Edit', edit_landlord_path(landlord) %></td>
        <td style="text-align:center"><%= link_to 'Destroy', landlord, method: :delete, data:{ confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div align = "center">
<%= link_to 'New Landlord', new_landlord_path %>
</div>

app/views/landlords/new.html.erb
<div align = "center">
<h1>New Landlord</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

</div>

app/views/landlords/show.html.erb
<table class = "table table-bordered">
   <caption>Landlord Details</caption>
   
   <thead>
      <tr>
         <th style="text-align:center"> <strong>Name</strong>  </th>
         <th style="text-align:center"> <strong>Email</strong> </th>
         <th style="text-align:center"> <strong>Phone</strong> </th>
		
      </tr>
   </thead>
   
   <tbody>
      <tr>
         <td> <%= @landlord.name %> </td>
         <td><%= @landlord.email %></td>
         <td> <%= @landlord.phone %></td>
		
		 
      </tr>
      

   </tbody>
	
</table>

<%= link_to 'Edit', edit_landlord_path(@landlord) %> |
<%= link_to 'Back', landlords_path %>